name: CI Pipeline

# The event that triggers the workflow
on:
  push:
    branches:
      - main

# Define the jobs to run
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the application
    - name: Build
      run: dotnet build --no-restore

    # Step 5: Run tests
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
