name: Build and Test

on: [push]

jobs:
  setup:
    uses: ./.github/workflows/setup-dotnet.yml

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build the application
        run: dotnet build
